### ISSUE TITLE
Event user clicked ads

### ISSUE THREAD

**Issue by namhd1992** [MatheusAlvesA/react-native-androide#6]
how to detect user click ads
Thanks

**Comment by MatheusAlvesA** [comment]
Hi.

In case of the banner, you can use the onClick listerner.
Example:
```Javascript
<AdMobBanner
   adSize="banner"
   adUnitID="ca-app-pub-3940256099942544/6300978111"
   onClick={() => {
        // Code to be execute when the user clicks on the Ad
  }}
/>
```

If you are using the Interstitial Ad, you can do something like this:

```Javascript
    AdMobInterstitial.setClickedListener(
       () => {
          // Code to be execute when the user clicks on the Ad
       }
    );
```

But, if you are using the Rewarded Video: There is no event listener to the click event. You can use `setRewardedListener()` function to know when the user watched the video until the end.

**Comment by namhd1992** [comment]
Thanks
Vào 21:21, T.2, 16 Th9, 2019 Matheus Alves <notifications@github.com> đã
viết:
